### PR TITLE
AboutDialog Lab

### PR DESCRIPTION
**Pull request by afrlan**
This is initial implementation of AboutBox:

It retrieves info from Assembly, GitHub and VSMarketplace.
It has basic parsing of Changelog.md file. (Sufficient to present all changes currently present; will be expanded in future iterations.)

### CODE REVIEW

**Comment by afrlan** [comment]
I closed it because I thought that newest commit isn't included. I was wrong.

**Comment by ironcev** [comment]
Hi @afrlan, thanks a lot for this pull request! I can hardly wait to have the dialog released :-)

The requirements are fulfilled very precisely I must say (up to one single detail ;-)). Also, the code is written in a very clean and understandable way.

My remarks are given below. As you will see, I would like to use the About Dialog to set the bar and guidelines for all the upcoming dialogs and UI elements in Sharpen. (And there will be plenty of them.)

Since this is a PR for the Lab and not for the final dialog there are just a few minor things to improve to fulfill the Lab requirements. Also, I would suggest implementing the missing functionality in the Lab project. So, to get the PR merged only the first two group should be implemented:

- Fulfill Lab Requirements
- Implement Missing Functionality


However, since you will soon integrate the dialog into the Sharpen project I will use this opportunity to give some hints related to the code so that it complies with (at the moment unwritten) Sharpen coding guidelines. Some architectural points are there as well. Fill free to implement these steps in a separate PR or in this one, as per your convenience.

# Fulfill Lab Requirements

- [ ] Name the folder *AboutDialog* instead of *AboutBoxTest*. Labs do not end in Test and Dialog and not Box is used in the issue definition.
- [ ] Delete the copy of Sharpen's README.md. It was used for experimenting in MainWindow.xaml.cs but that code is commented out (and should also be deleted - see below).
- [ ] Add Lab README.md. Each Lab project must have a readme that explains its purpose, usage, and outcome. As a reference take a look at READMEs in other Sharpen Lab projects. This is also [a good example of a Lab README](https://github.com/nseedio/nseed/blob/master/lab/UnobtrusiveConsoleColors/README.md).

# Implement Missing Functionality

- [ ] Handle values coming from GitHub and VSMarketplace in case of error.

According to the [requirements](https://github.com/sharpenrocks/Sharpen/issues/32):

> If not or if any error happens during fetching do not display anything.

There will surely be issues when fetching data from GitHub and VSMarketplace. The current implementation is optimistic and assumes that the data will always be there. Implement a robust solution in case of errors. Per spec in that case e.g. number of stars etc. will simply not be displayed.

- [ ] Get the description from the assembly description (`AssemblyDescriptionAttribute`) instead from GitHub. As explained we assume that fetching data from GitHub will not always work and unlike the number of stars which can be ignored and not displayed we want the description to always be displayed.

# Coding Guidelines

- [ ] Remove unused usings in:
  - [ ] App.xaml.cs
  - [ ] MainWindow.xaml.cs
  - [ ] MarkdownToFlowDocument.cs
- [ ] Remove unused XAML elements in:
  - [ ] App.xaml
  - [ ] MainWindow.xaml
- [ ] Remove useless comments in:
  - [ ] App.xaml.cs
  - [ ] MainWindow.xaml.cs
- [ ] Have consistent tags closings on MainWindow.xaml. Sometimes it is "/>" and sometimes " />".
- [ ] Remove `this` qualifier in MainWindow.xaml.cs where not needed.
- [ ] Remove commented code from MainWindow.xaml.cs.
- [ ] Write code comments as full sentences with punctuation e.g. ending with a dot.
- [ ] Remove unused variable filePath in MarkdownToFlowDocument.

# Use Consistent Naming

- [ ] In App.xaml.cs:
  - [ ] GitAuthToken -> GitHubAuthToken
  - [ ] GitLogin -> GitHubLogin
  - [ ] GitRepository -> GitHubRepository
  - [ ] VSMarketplaceID -> VSMarketplaceId
- [ ] Everywhere (e.g. in MainWindow.xaml) Github -> GitHub
- [ ] In MainWindow.xaml.cs:
  - [ ] ...Git... -> ...GitHub...
  - [ ] ...ChangeLog... -> ...Changelog...
- [ ] Use consistent casing in icon names consisting of two parts. E.g. Icon.github.png and Rating.FullStar.png is not consistent. Proposal is to go for the second, PascalCase, option and have Icon.GitHub and Icon.WWW.
- [ ] Have more expressive names for images:
  - [ ] Icon.png -> SharpenLogo.png
  - [ ] PreviewImage.png -> SharpenLogo.Preview.png ??
  - [ ] SharpenPackage.ico can stay as it is since it will be reused under that name once the dialog is added to the Sharpen project.
- [ ] Rename MarkdownToFlowDocument to MarkdownToFlowDocumentConverter.
- [ ] Rename MainWindow to AboutDialog.

# Architectural Guidelines

- [ ] Use [Configuration Sections](https://docs.microsoft.com/en-us/previous-versions/2tw134k3(v=vs.140)?redirectedfrom=MSDN) to pack together configuration settings used by the AboutDialog. Name the section *AboutDialog*. In the Lab, the dialog lives alone and having the settings as a plain non-grouped list is perfectly fine. But in Sharpen we will one day have several different configurations for different purposes and parts of Sharpen and we will need to group them in sections.
- [ ] Use [MVVM with data binding](https://docs.microsoft.com/en-us/dotnet/desktop-wpf/data/data-binding-overview). In this particular case, it means using data binding instead of accessing UI controls in code. For this relatively simple dialog accessing the controls directly is straightforward. But in general, we will have more complex UI in Sharpen and we want to use this Dialog for setting the guidelines for UI development. Basically, we want to use MVVM in a healthy combination with event handlers.

There are some other architectural considerations that will become relevant once we put the dialog into Sharpen. We will discuss them at that point.

Also, there will be some interesting extensions for the Markdown converter. But I like your approach to extend the parser in future iterations so we can discuss these extensions once the dialog is fully integrated into Sharpen.

Let me know if you have any additional questions.

**Comment by afrlan** [comment]
Hello!

I've implemented all but "Use MVVM with data binding."

Config sections seamed like an overkill; I think that prefixing keys with "AboutDialog." would accomplish the same grouping goal. However, since this is a learning exercise, I implemented it. (In production, type will be in another assembly, so "Sharpen.AboutDialog+ConfigSection, AboutDialog" will have to be changed accordingly.) Unfortunately, "The configuration section cannot contain a CDATA or text element." so something like
```
<aboutDialog>
    <gitHubAuthToken>value</gitHubAuthToken> 
</aboutDialog>
```
is not implementable (it seems).

I'll try to resolve data binding this week.

**Comment by ironcev** [comment]
Hi @afrlan,

Thanks for providing the updated PR! As I mentioned before, I don't see MVVM as necessary to close this PR ;-)
The closed points are checked as done in my original comment. As you can see, some points are still left open. In my opinion, they need a bit more touch. In particular, I discuss in more detail the handling of the error case when fetching data from GitHub and VSMarketplace.

Also, in the previous feedback, I forgot to mention that the copyright, same as the description, should be taken from the assembly. So I've added that point to the original comment.

Please take a look at the extended original comment. The new remarks are written in *italics*.

Regarding the latest commits, here is my short feedback.
- [ ] Instead of `assembly.GetCustomAttributes(typeof(AssemblyDescriptionAttribute), false).OfType<AssemblyDescriptionAttribute>().FirstOrDefault();` we can use `assembly.GetCustomAttribute<AssemblyDescriptionAttribute>();`.
- [ ] Rename ConfigSection to AboutDialogConfigurationSection and make it non-nested. (Also, remove unused usings from the class file.)

**Comment by afrlan** [comment]
Hi,

Since I'm not used to proper commit, instead of resolving one issue at a time I fixed all and then made one commit. (I understand that many commits per issue are better than one commit per multiple issues.)

Other than that, I believe I fixed all unchecked boxes. Except databinding, that will be imlplemented later, when need arises (soon-ish, I expect).

Also, SomethingID will, probably, be the most difficult thing to change to SomenthingId.

**Pull request merged**
